### ISSUE TITLE
looking for non-existent .mol file when using -p xxx.pdb input

### ISSUE THREAD

**Issue by rwood-97** [leelasd/LigParGen-CommandFiles#1]
Hello,

I have installed the LigParGen command line program and am getting the following error when trying to parameterise my pdb file:

```
ligpargen --pdb test.pdb -c -1 -o 3 -r TST
Traceback (most recent call last):
  File "/Users/rosiewood/miniconda3/bin/LigParGen", line 8, in <module>
    sys.exit(main())
  File "/Users/rosiewood/miniconda3/lib/python3.8/site-packages/LigParGen/Converter.py", line 90, in main
    convert(**vars(args))
  File "/Users/rosiewood/miniconda3/lib/python3.8/site-packages/LigParGen/Converter.py", line 153, in convert
    GenMolRep(pdb, optim, resname, charge)
  File "/Users/rosiewood/miniconda3/lib/python3.8/site-packages/LigParGen/CreatZmat.py", line 51, in GenMolRep
    AsitIsZmat(ifile,optim,resid) 
  File "/Users/rosiewood/miniconda3/lib/python3.8/site-packages/LigParGen/CreatZmat.py", line 29, in AsitIsZmat
    mollines = open(iform[0] + '.mol', 'r').readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'test.mol'
(base) -> [1]
```

Thanks in advance

**Comment by marcodigennaro** [comment]
Try this newer version https://github.com/Isra3l/ligpargen
